services:
  backend:
    build: ./backend
    container_name: oauth-backend
    ports:
      - "8003:8000"
    environment:
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI:-http://localhost:8003/auth/callback}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8003}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-organizations}
      - AZURE_TENANT_TYPE=${AZURE_TENANT_TYPE:-multi}
      - ENABLE_GROUPS_CLAIM=${ENABLE_GROUPS_CLAIM:-false}
      - ENABLE_ROLES_CLAIM=${ENABLE_ROLES_CLAIM:-false}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE=${VITE_API_BASE}
        - VITE_BASE_PATH=${VITE_BASE_PATH:-/}
    container_name: oauth-frontend
    ports:
      - "3003:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3